name: Svelte Check
on: [push]
jobs:
  run_svelte_check:
    name: Run svelte-check
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4
      - name: ğŸ‘® Run svelte-check
        run: |
          npm run check
      - run: echo "ğŸ This job's status is ${{ job.status }}."
